# -*- coding: utf-8 -*-
"""Fixed_Income_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftcuqe2NASJr0Aw66rLmoh47Zh9iRdnv
"""

import numpy as np
import matplotlib.pyplot as plt

def calcular_precio_bono(nominal, tasa_cupon, ytm, años):
    cupón = nominal * tasa_cupon
    tiempos = np.arange(1, años + 1)
    flujos = np.full(años, cupón)
    flujos[-1] += nominal
    return np.sum(flujos / (1 + ytm)**tiempos)

# --- CONFIGURACIÓN DEL BONO ---
NOMINAL = 1000
CUPON = 0.05  # 5%
AÑOS = 10
YTM_ACTUAL = 0.04  # 4% (Tasa de mercado hoy)

# 1. Simulación de diferentes tasas de mercado (eje X)
tasas_mercado = np.linspace(0.01, 0.10, 100)  # Del 1% al 10%
precios = [calcular_precio_bono(NOMINAL, CUPON, r, AÑOS) for r in tasas_mercado]

# 2. Cálculo de sensibilidad (Shock de tipos)
precio_base = calcular_precio_bono(NOMINAL, CUPON, YTM_ACTUAL, AÑOS)
precio_shock_arriba = calcular_precio_bono(NOMINAL, CUPON, YTM_ACTUAL + 0.01, AÑOS)
perdida = precio_shock_arriba - precio_base

print(f"Precio actual (YTM 4%): {precio_base:.2f}€")
print(f"Si los tipos suben al 5%, el bono vale: {precio_shock_arriba:.2f}€")
print(f"Impacto en Balance (P&L): {perdida:.2f}€ por cada bono.")

# 3. Gráfico de Convexidad
plt.figure(figsize=(10, 6))
plt.plot(tasas_mercado, precios, label='Precio del Bono', color='blue', lw=2)
plt.axvline(YTM_ACTUAL, color='red', linestyle='--', label=f'YTM Actual ({YTM_ACTUAL*100}%)')
plt.scatter(YTM_ACTUAL, precio_base, color='red')

plt.title('Relación Inversa: Precio vs Tipos de Interés (Convexidad)')
plt.xlabel('Tasa de Mercado (YTM)')
plt.ylabel('Precio del Bono (€)')
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()