# -*- coding: utf-8 -*-
"""FMP_async_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgjigxbhSm1o7qugyA0eYLs3oQQRRay8
"""

import logging
import httpx
import requests
from fastapi import FastAPI, HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, Field
from starlette.status import HTTP_401_UNAUTHORIZED

# --- 1. CONFIGURACIÓN DEL SISTEMA DE AUDITORÍA (LOGGING) ---
# Configuramos para que guarde los logs en un archivo de texto con un formato limpio
logging.basicConfig(
    filename='auditoria_tesoreria.log',
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

app = FastAPI(
    title="Asyncronous, secure, real-time API connection service",
    description="API segura con sistema de auditoría y conectada a Financial Modeling Prep Database."
)

# --- 2. CONFIGURACIÓN DE SEGURIDAD ---
security_scheme = HTTPBearer()
TOKEN_SECRETO_INTERNO = "SherlockHolmes18"


async def verificar_token(credentials: HTTPAuthorizationCredentials = Depends(security_scheme)):
    if credentials.credentials == TOKEN_SECRETO_INTERNO:
        return credentials.credentials

    # AUDITORÍA: Registramos un intento de hackeo o acceso no autorizado
    logging.warning(
        "ALERTA DE SEGURIDAD: Intento de acceso denegado con token incorrecto o ausente.")
    raise HTTPException(
        status_code=HTTP_401_UNAUTHORIZED,
        detail="Token de seguridad inválido o ausente. Acceso denegado."
    )

# --- 3. CONFIGURACIÓN DE DATA EXCLUSIVA ---
FMP_API_KEY = "xi7IGuHipNB4H6FuWcctxKy1GbOLg9R5"

# Base de datos local simulada para el endpoint clásico
precios_mercado = {"BBVA": 9.50, "SAN": 4.20, "TEF": 3.85}

# --- 4. ENDPOINTS CON AUDITORÍA ACTIVA ---


@app.get("/precio/{ticker}")
async def obtener_precio_local(ticker: str):
    ticker_upper = ticker.upper()

    if ticker_upper not in precios_mercado:
        # AUDITORÍA: Registramos que buscaron un ticker inválido (como te pasó con MSFT)
        logging.error(
            f"CONSULTA FALLIDA: El activo '{ticker_upper}' no existe en el sistema local.")
        raise HTTPException(
            status_code=404, detail="Activo financiero no encontrado en el sistema")

    precio = precios_mercado[ticker_upper]

    # AUDITORÍA: Registro de consulta exitosa
    logging.info(
        f"CONSULTA LOCAL EXITOSA: Se ha servido el precio de {ticker_upper} ({precio} EUR).")
    return {"activo": ticker_upper, "precio": precio, "fuente": "Filtro Interno"}


@app.get("/precio-real/{ticker}")
async def obtener_precio_fmp(ticker: str, token: str = Depends(verificar_token)):
    ticker_upper = ticker.upper()
    url_fmp = f"https://financialmodelingprep.com/stable/quote"
    params = {
        "symbol": ticker_upper,
        "apikey": FMP_API_KEY
    }

    try:
        async with httpx.AsyncClient() as client:
            respuesta = await client.get(url_fmp, params=params, timeout=10.0)

        if respuesta.status_code != 200:
            logging.error(
                f"FALLO DE RESPUESTA FMP: Código de estado {respuesta.status_code} para '{ticker_upper}'.")
            raise HTTPException(
                status_code=respuesta.status_code,
                detail=f"FMP API returned status code {respuesta.status_code}"
            )

        datos = respuesta.json()

        # FMP returns an empty list [] if ticker doesn't exist or if daily limits are reached
        if not datos or isinstance(datos, dict) and "Error Message" in datos:
            logging.warning(
                f"CONSULTA FALLIDA: No se encontraron datos para el activo '{ticker_upper}'.")
            raise HTTPException(
                status_code=404, detail=f"No valid data returned for '{ticker_upper}'. Verify ticker or key limits.")

        info_activo = datos[0]

        logging.info(
            f"CONSULTA FMP EXITOSA: Se sirvió el precio en tiempo real de {ticker_upper}.")

        return {
            "activo": info_activo.get("symbol"),
            "nombre_empresa": info_activo.get("name"),
            "precio_mercado": info_activo.get("price"),
            "cambio_porcentual": info_activo.get("changesPercentage"),
            "volumen_diario": info_activo.get("volume"),
            "estado_seguridad": "Conexión Cifrada y Verificada con Token Bearer",
            "fuente_origen": "Financial Modeling Prep API Real"
        }

    except httpx.RequestError as exc:
        logging.critical(
            f"FALLO DE INFRAESTRUCTURA DE RED: Error al conectar con FMP. Detalles: {exc}")
        raise HTTPException(
            status_code=503, detail=f"Network infrastructure error: {exc}")
