# -*- coding: utf-8 -*-
"""portfolio_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW6Gllv1hAWgAkC_f9m7qV4VBUI042F2
"""

# & "C:\Users\Jaime\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts\streamlit.exe" run portfolio_app.py

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Portfolio Dashboard", layout="wide")

st.title("📊 Multi-Asset Portfolio Dashboard")

# Initialize portfolio
if "portfolio" not in st.session_state:
    st.session_state.portfolio = []

# --- Input Section ---
st.header("Add a Position")
ticker = st.text_input("Ticker (e.g. AAPL)")
shares = st.number_input("Shares", min_value=0.0, step=1.0)
cost_basis = st.number_input("Cost Basis ($)", min_value=0.0)

if st.button("Add to Portfolio"):
    st.session_state.portfolio.append({
        "ticker": ticker.upper(),
        "shares": shares,
        "cost_basis": cost_basis
    })
    st.success(f"Added {ticker.upper()} to portfolio!")

# --- MAIN DASHBOARD ---
if len(st.session_state.portfolio) == 0:
    st.info("Add positions using the input fields above to get started.")
else:
    df = pd.DataFrame(st.session_state.portfolio)

 # Fetch latest prices
    st.header("💵 Live Market Data")
    prices = []
    for t in df["ticker"]:
        data = yf.Ticker(t).history(period="1d")
        price = data["Close"].iloc[-1] if not data.empty else None
        prices.append(price)

    df["price"] = prices
    df["market_value"] = df["price"] * df["shares"]
    df["total_cost"] = df["cost_basis"] * df["shares"]
    df["unrealized_gain"] = df["market_value"] - df["total_cost"]
    df["return_pct"] = (df["unrealized_gain"] / df["total_cost"]) * 100

    # Layout
    col1, col2 = st.columns(2)

    # --- Portfolio Table ---
    with col1:
        st.subheader("📘 Portfolio Table")
        st.dataframe(df.style.format({
            "price": "${:,.2f}",
            "market_value": "${:,.2f}",
            "total_cost": "${:,.2f}",
            "unrealized_gain": "${:,.2f}",
            "return_pct": "{:,.2f}%"
        }))

    # --- Allocation Pie Chart ---
    with col2:
        st.subheader("📌 Allocation by Market Value")
        fig = px.pie(
            df,
            names="ticker",
            values="market_value",
            hole=0.4,
            title="Portfolio Allocation"
        )
        st.plotly_chart(fig, use_container_width=True)

    # --- Total Portfolio KPIs ---
    st.header("📈 Portfolio Summary")

    total_value = df["market_value"].sum()
    total_cost = df["total_cost"].sum()
    total_gain = total_value - total_cost
    total_return_pct = (total_gain / total_cost) * 100

    colA, colB, colC, colD = st.columns(4)
    colA.metric("Total Market Value", f"${total_value:,.2f}")
    colB.metric("Total Cost Basis", f"${total_cost:,.2f}")
    colC.metric("Total Gain/Loss", f"${total_gain:,.2f}")
    colD.metric("Total Return (%)", f"{total_return_pct:.2f}%")

    # --- Portfolio Performance Over Time ---
    st.header("📉 Historical Performance")

    hist_data = {}

    for t, shares in zip(df["ticker"], df["shares"]):
        ticker_obj = yf.Ticker(t)
        hist = ticker_obj.history(period="1y")["Close"]
        if not hist.empty:
            hist_data[t] = hist * shares

    if len(hist_data) > 0:
        hist_df = pd.DataFrame(hist_data)
        hist_df["Total Value"] = hist_df.sum(axis=1)

        fig2 = px.line(hist_df, y="Total Value", title="Portfolio Value (1 Year)")
        st.plotly_chart(fig2, use_container_width=True)
    else:
        st.info("Not enough historical data available for performance chart.")