# -*- coding: utf-8 -*-
"""Kelly_criterion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ATlNgT9e_P-6PvUcM6gvU7hs656yO0V
"""

import numpy as np

# Parameters from our previous simulation
mu = 0.0005 * 252  # Annualized drift (~12.6%)
sigma = 0.01 * np.sqrt(252)  # Annualized volatility (~15.8%)

# 1. Calculate Kelly Fraction
kelly_f = mu / (sigma**2)

# 2. The "Half-Kelly" (Industry Standard)
# Banks almost never use 'Full Kelly' because it's too volatile.
# They use 'Half-Kelly' (0.5 * f*) to stay safe.
safe_f = kelly_f * 0.5

print(f"Optimal Kelly Fraction (Full): {kelly_f:.2f}")
print(f"Safe Banking Fraction (Half-Kelly): {safe_f:.2f}")

#Optimal Capital Allocation: Implemented the Kelly Criterion to optimize position sizing and maximize long-term geometric growth.

#Risk Mitigation: Applied "Fractional Kelly" sizing to reduce the probability of ruin and account for model uncertainty (fat tails).

#Capital Management: Modeled the trade-off between leverage and drawdown, ensuring the strategy remains within the bank's risk appetite framework.