# -*- coding: utf-8 -*-
"""fastapi_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvK1V3D4Ncd-X8KsdecJqOfua92_IHyS
"""

import random
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# 1. Inicializamos la aplicación FastAPI
app = FastAPI(
    title="API de Precios en Tiempo Real - Mesa de Tesorería",
    description="Simulador para consultar y actualizar precios de activos financieros de forma segura."
)

# 2. Creamos el modelo de datos con Pydantic (Validación estricta)
class SolicitudPrecio(BaseModel):
    ticker: str = Field(..., min_length=3, max_length=5, description="El código de la acción, ej: BBVA")

class ActualizacionPrecio(BaseModel):
    ticker: str
    nuevo_precio: float = Field(..., gt=0, description="El precio debe ser un número mayor que cero")

# Base de datos simulada en memoria (Diccionario)
precios_mercado = {
    "BBVA": 9.50,
    "SAN": 4.20,
    "TEF": 3.85
}

# 3. ENDPOINT 1 (GET): Consumir datos (Para el robot/modelo de trading)
@app.get("/precio/{ticker}")
async def obtener_precio(ticker: str):
    ticker_upper = ticker.upper()

    if ticker_upper not in precios_mercado:
        raise HTTPException(status_code=404, detail="Activo financiero no encontrado en el sistema")

    # Simulamos una pequeña variación en tiempo real (ruido de mercado)
    precio_actual = precios_mercado[ticker_upper] + random.uniform(-0.05, 0.05)

    return {
        "activo": ticker_upper,
        "precio_tiempo_real": round(precio_actual, 4),
        "proveedor": "Filtro Interno - Arktic"
    }

# 4. ENDPOINT 2 (POST): Enviar/Modificar datos (Para la base de datos segura)
@app.post("/actualizar-precio/")
async def actualizar_precio(datos: ActualizacionPrecio):
    ticker_upper = datos.ticker.upper()

    # Modificamos nuestra base de datos simulada
    precios_mercado[ticker_upper] = datos.nuevo_precio

    return {
        "mensaje": f"Precio de {ticker_upper} actualizado correctamente de forma segura",
        "nuevo_precio_fijado": datos.nuevo_precio
    }