# -*- coding: utf-8 -*-
"""onlineportfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10otEIM7AoeJ9KfGLD_CrFibJxUIH-DRA
"""

import os

# Install Streamlit if not already installed
!pip install streamlit pyngrok -qq

from pyngrok import ngrok

# Streamlit app content as a string
streamlit_app_code = '''
import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Portfolio Dashboard", layout="wide")

st.title("📊 Multi-Asset Portfolio Dashboard")

# Initialize portfolio
if "portfolio" not in st.session_state:
    st.session_state.portfolio = []

# --- Input Section ---
st.header("Add a Position")
ticker = st.text_input("Ticker (e.g. AAPL)")
shares = st.number_input("Shares", min_value=0.0, step=1.0)
cost_basis = st.number_input("Cost Basis ($", min_value=0.0)

if st.button("Add to Portfolio"):
    st.session_state.portfolio.append({
        "ticker": ticker.upper(),
        "shares": shares,
        "cost_basis": cost_basis
    })
    st.success(f"Added {ticker.upper()} to portfolio!")

# --- MAIN DASHBOARD ---
if len(st.session_state.portfolio) == 0:
    st.info("Add positions using the input fields above to get started.")
else:
    df = pd.DataFrame(st.session_state.portfolio)

 # Fetch latest prices
    st.header("💵 Live Market Data")
    prices = []
    for t in df["ticker"]:
        data = yf.Ticker(t).history(period="1d")
        price = data["Close"].iloc[-1] if not data.empty else None
        prices.append(price)

    df["price"] = prices
    df["market_value"] = df["price"] * df["shares"]
    df["total_cost"] = df["cost_basis"] * df["shares"]
    df["unrealized_gain"] = df["market_value"] - df["total_cost"]
    df["return_pct"] = (df["unrealized_gain"] / df["total_cost"]) * 100

    # Layout
    col1, col2 = st.columns(2)

    # --- Portfolio Table ---
    with col1:
        st.subheader("📘 Portfolio Table")
        st.dataframe(df.style.format({
            "price": "${:,.2f}",
            "market_value": "${:,.2f}",
            "total_cost": "${:,.2f}",
            "unrealized_gain": "${:,.2f}",
            "return_pct": "{:,.2f}%"
        }))

    # --- Allocation Pie Chart ---
    with col2:
        st.subheader("📌 Allocation by Market Value")
        fig = px.pie(
            df,
            names="ticker",
            values="market_value",
            hole=0.4,
            title="Portfolio Allocation"
        )
        st.plotly_chart(fig, use_container_width=True)

    # --- Total Portfolio KPIs ---
    st.header("📈 Portfolio Summary")

    total_value = df["market_value"].sum()
    total_cost = df["total_cost"].sum()
    total_gain = total_value - total_cost
    total_return_pct = (total_gain / total_cost) * 100

    colA, colB, colC, colD = st.columns(4)
    colA.metric("Total Market Value", f"${total_value:,.2f}")
    colB.metric("Total Cost Basis", f"${total_cost:,.2f}")
    colC.metric("Total Gain/Loss", f"${total_gain:,.2f}")
    colD.metric("Total Return (%)", f"{total_return_pct:.2f}%")

    # --- Portfolio Performance Over Time ---
    st.header("📉 Historical Performance")

    hist_data = {}

    for t, shares in zip(df["ticker"], df["shares"]):
        ticker_obj = yf.Ticker(t)
        hist = ticker_obj.history(period="1y")["Close"]
        if not hist.empty:
            hist_data[t] = hist * shares

    if len(hist_data) > 0:
        hist_df = pd.DataFrame(hist_data)
        hist_df["Total Value"] = hist_df.sum(axis=1)

        fig2 = px.line(hist_df, y="Total Value", title="Portfolio Value (1 Year)")
        st.plotly_chart(fig2, use_container_width=True)
    else:
        st.info("Not enough historical data available for performance chart.")
'''

# Write the Streamlit app code to a file
with open("app.py", "w") as f:
    f.write(streamlit_app_code)

# Check if an ngrok token is set as an environment variable
# You might need to set your NGROK_AUTH_TOKEN in your Colab secrets or directly here.
# For example: ngrok.set_auth_token("YOUR_AUTHTOKEN_HERE")
if "NGROK_AUTH_TOKEN" in os.environ:
    ngrok.set_auth_token(os.environ["NGROK_AUTH_TOKEN"])
    print("Ngrok authentication token found and set.")
else:
    print("Warning: NGROK_AUTH_TOKEN environment variable not found. You might need to set it for ngrok to work properly.")
    print("Please get your authtoken from https://ngrok.com/signup and set it via `ngrok.set_auth_token('YOUR_AUTHTOKEN_HERE')` or as a Colab secret.")

# Run Streamlit in the background
!nohup streamlit run app.py & > /dev/null 2>&1 &

# Wait for Streamlit to start and expose it via ngrok
import time
time.sleep(5) # Give Streamlit a moment to start

# Open a ngrok tunnel to the Streamlit port (default 8501)
try:
    public_url = ngrok.connect(addr="8501", proto="http")
    print(f"\nStreamlit App is live at: {public_url}")
    print("Copy this URL and paste it into your browser to view the dashboard.")
    print("Note: You might need to refresh your browser after navigating to the URL.")
    print("To stop ngrok tunnel, use `ngrok.kill()`")
except Exception as e:
    print(f"Error creating ngrok tunnel: {e}")
    print("Please ensure ngrok authentication token is set correctly.")

"""### Set your ngrok Authentication Token

To allow `ngrok` to create a public URL for your Streamlit app, you need to provide an authentication token.

1.  **Get your Authtoken:** If you don't have one, sign up at [ngrok.com](https://ngrok.com/signup) and get your authtoken from your dashboard: [https://dashboard.ngrok.com/get-started/your-authtoken](https://dashboard.ngrok.com/get-started/your-authtoken).

2.  **Set the Token in Colab:** You can set it in one of two ways:
    *   **Recommended (using Colab Secrets):** Click the '🔑' icon on the left sidebar, add a new secret, name it `NGROK_AUTH_TOKEN`, and paste your token as the value. Make sure to enable 'Notebook access'. This keeps your token secure and private.
    *   **Directly in code (less secure):** You can uncomment and modify the line in the code cell below to directly set your token. Replace `"YOUR_AUTHTOKEN_HERE"` with your actual token.

After setting the token, please **re-run the previous code cell (`caiFd5HyU425`)** to start your Streamlit application and get the public URL.
"""

# Option 1 (Recommended): If you've set NGROK_AUTH_TOKEN in Colab secrets, no action is needed here.
# The previous cell will automatically pick it up from os.environ.

# Option 2 (Less Secure): Manually set your ngrok authtoken here if not using Colab secrets.
# from pyngrok import ngrok
# ngrok.set_auth_token("YOUR_AUTHTOKEN_HERE")
# print("ngrok authentication token set directly.")

# After setting the token (either via secrets or directly above),
# please re-run the cell `caiFd5HyU425` to launch your Streamlit app.

"""# Task
Run the Streamlit application from cell `caiFd5HyU425`.

## Run Streamlit App

### Subtask:
Run the Streamlit application from the provided notebook cell. This will launch the Streamlit dashboard on a local server, making it accessible via a URL. This URL is what you would use for embedding.

# Task
Please provide your ngrok authentication token. You can set it as a Colab secret named `NGROK_AUTH_TOKEN` (recommended) or paste it directly into cell `21e2eb57` by uncommenting the `ngrok.set_auth_token("YOUR_AUTHTOKEN_HERE")` line and replacing `"YOUR_AUTHTOKEN_HERE"` with your actual token. After setting the token, please confirm, and I will re-run the Streamlit application.

## Ensure ngrok token is set

### Subtask:
Configure the ngrok authentication token to allow the Streamlit application to be publicly exposed.

### Subtask
Configure the ngrok authentication token to allow the Streamlit application to be publicly exposed.

#### Instructions
To resolve the ngrok authentication error, please set your ngrok token using one of the following methods:
1.  **Recommended (Colab Secrets):** Click the '🔑' icon on the left sidebar, add a new secret, name it `NGROK_AUTH_TOKEN`, and paste your ngrok authentication token as the value. Make sure to enable 'Notebook access'.
2.  **Directly in code (Less Secure):** Go to cell `21e2eb57`, uncomment the line `# ngrok.set_auth_token("YOUR_AUTHTOKEN_HERE")`, and replace `"YOUR_AUTHTOKEN_TOKEN_HERE"` with your actual ngrok token.

After successfully setting the token using either method, please confirm that you have completed this step.

# Task
Verify that the `NGROK_AUTH_TOKEN` is correctly set, then re-run the Streamlit application in cell `caiFd5HyU425` to generate a public ngrok URL, and finally provide a React.js component to integrate and view the dashboard.

## Verify ngrok Authentication

### Subtask:
Verify if the `NGROK_AUTH_TOKEN` is correctly set to prevent further authentication errors when launching the tunnel.

### Subtask
Verify if the `NGROK_AUTH_TOKEN` is correctly set to prevent further authentication errors when launching the tunnel.

#### Instructions
1. **Check Colab Secrets (Recommended):** Click the '🔑' icon on the left sidebar. Ensure you have a secret named `NGROK_AUTH_TOKEN` with your token as the value, and that **'Notebook access'** is toggled on.
2. **Manual Configuration:** Alternatively, go to cell `21e2eb57`, uncomment the `ngrok.set_auth_token("YOUR_AUTHTOKEN_HERE")` line, and replace the placeholder with your actual token.
3. **Verification:** Run the following code to check if the token is detected:
```python
import os
print('Token found in environment:', 'NGROK_AUTH_TOKEN' in os.environ)
```

**Reasoning**:
I will provide a code block to verify if the NGROK_AUTH_TOKEN is correctly set in the environment or pyngrok configuration.
"""

import os
from pyngrok import conf, ngrok

# Check environment variable (Colab Secrets)
token_in_env = 'NGROK_AUTH_TOKEN' in os.environ

# Check pyngrok configuration file
config_path = conf.get_default().config_path
token_in_config = False
if os.path.exists(config_path):
    with open(config_path, 'r') as f:
        if 'authtoken' in f.read():
            token_in_config = True

print(f'NGROK_AUTH_TOKEN in environment: {token_in_env}')
print(f'Token found in pyngrok config: {token_in_config}')

if not (token_in_env or token_in_config):
    print('\n[!] Warning: No token detected. Please follow the instructions in the markdown cell above.')
else:
    print('\n[+] Token detected. You can now re-run cell caiFd5HyU425.')